networks:
  monitoring:

volumes:
  grafana_data:
  prometheus_data:

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring
    ports:
      -  "9090:9090"
  grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      -  "3000:3000"
    networks:
      - monitoring
  node:
    image: prom/node-exporter
    command:
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.systemd'
      - '--collector.systemd.unit-whitelist=.+\.service'
    volumes:
      - /etc/hostname:/etc/nodename
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    networks:
      - monitoring



