services:
  nginx:
    image: ${PREFIX}nginx:1.27.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    ports:
      - "80:80"

  
  elasticsearch:
    image: ${PREFIX}elasticsearch:8.17.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: ${PREFIX}kibana:8.17.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  fluentd:
    image: ${PREFIX}fluentd:v1.18-1
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/var/log/nginx
    environment:
      FLUENTD_CONF: "fluent.conf"
    ports:
      - "24224:24224"
