services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./php:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    volumes:
      - ./php:/usr/share/nginx/html