version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    networks:
      - blog-network

  mongo:
    image: mongo
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
