global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'ruby_app'
    static_configs:
      - targets: ['ruby_app:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
